apiVersion: v1
name: cert-manager-webhook-glesys
# version is set automatically by the Git tag
version: 1.3.0
# appVersion is set automatically by the Git tag
appVersion: "1.3.0"
description: A Helm chart for the GleSYS DNS webhook for cert-manager DNS01 challenges
